services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB:       staffcar
      POSTGRES_USER:     caruser
      POSTGRES_PASSWORD: carpass123
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: achirawit1/staffcar-backend:latest
    restart: unless-stopped
    environment:
      DB_HOST:     db
      DB_PORT:     5432
      DB_NAME:     staffcar
      DB_USER:     caruser
      DB_PASSWORD: carpass123
      PORT:        3000
    depends_on:
      - db

  frontend:
    image: achirawit1/staffcar-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data: